defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: reading_dev
  <<: *defaults

test:
  database: reading_test
  <<: *defaults

staging:
  database: reading_staging
  <<: *defaults

production:
  database: reading_prod
  <<: *defaults

